In [2]:
l = [1,2,3,4,5,6]
l[4:]

[5, 6]

In [1]:
import torch
from torch.functional import F

a = F.tanh(torch.tensor([300, -100]))
print(a)
lim = torch.tensor([500, 10])
a = a * lim
# print(lim)
# print(lim[:, 0])
# a = torch.where(a < 0, torch.clamp_min(a, lim[:, 0]), torch.clamp_max(a, lim[:, 1]))
# a
a

tensor([ 1., -1.])


tensor([500., -10.])

In [13]:
from dataclasses import dataclass
@dataclass
class Observations:
    relative_position: torch.Tensor
    relative_velocity: torch.Tensor
    relative_acceleration: torch.Tensor
    relative_orientation: torch.Tensor
    target_position: torch.Tensor

    def __repr__(self) -> str:
        return str(self.__dict__)

obs = Observations(
    relative_position=torch.tensor([[1, 2, 3]]),
    relative_velocity=torch.tensor([4, 5, 6]),
    relative_acceleration=torch.tensor([7, 8, 9]),
    relative_orientation=torch.tensor([10, 11, 12]),
    target_position=torch.tensor([13, 14, 15])
)
obser = {"observation": obs}

In [51]:
torch.randint(0, 10, (3,)).float(),

tensor([0.8444, 0.2738, 0.3173])